-- =============================================
-- TITANIC VISTARA PROJECT - COMPLETE SQL CODE
-- Run all statements in order
-- =============================================

CREATE DATABASE IF NOT EXISTS TITANIC_VISTARA_PROJECT;
USE DATABASE TITANIC_VISTARA_PROJECT;

CREATE SCHEMA IF NOT EXISTS FEATURES;
USE SCHEMA FEATURES;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;

-- =============================================
-- STEP 1: CREATE RAW TABLE AND LOAD DATA
-- =============================================

CREATE OR REPLACE TABLE RAW_TITANIC (
    PASSENGERID INTEGER,
    SURVIVED INTEGER,
    PCLASS INTEGER,
    NAME VARCHAR(200),
    SEX VARCHAR(10),
    AGE FLOAT,
    SIBSP INTEGER,
    PARCH INTEGER,
    TICKET VARCHAR(50),
    FARE FLOAT,
    CABIN VARCHAR(50),
    EMBARKED VARCHAR(5)
);

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    FIELD_DELIMITER = ',';

CREATE OR REPLACE STAGE DATA_STAGE 
    FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_TITANIC 
FROM @DATA_STAGE/Titanic-Dataset.csv 
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS RAW_TOTAL_ROWS FROM RAW_TITANIC;
SELECT * FROM RAW_TITANIC LIMIT 5;

-- =============================================
-- STEP 2: BASIC FEATURE ENGINEERING
-- =============================================

CREATE OR REPLACE TABLE FEATURES_BASIC AS
SELECT 
    PASSENGERID,
    SURVIVED,
    PCLASS,
    SEX,
    AGE,
    SIBSP,
    PARCH,
    FARE,
    EMBARKED,
    
    (SIBSP + PARCH + 1) AS FAMILY_SIZE,
    
    CASE 
        WHEN (SIBSP + PARCH) = 0 THEN 1 
        ELSE 0 
    END AS IS_ALONE,
    
    CASE 
        WHEN CABIN IS NOT NULL THEN 1 
        ELSE 0 
    END AS HAS_CABIN,
    
    CASE 
        WHEN NAME LIKE '%Mr.%' THEN 'Mr'
        WHEN NAME LIKE '%Mrs.%' THEN 'Mrs'
        WHEN NAME LIKE '%Miss.%' THEN 'Miss'
        WHEN NAME LIKE '%Master.%' THEN 'Master'
        ELSE 'Other'
    END AS TITLE
    
FROM RAW_TITANIC;

SELECT COUNT(*) AS FEATURES_BASIC_ROWS FROM FEATURES_BASIC;
SELECT * FROM FEATURES_BASIC LIMIT 5;

-- =============================================
-- STEP 3: AGGREGATED FEATURES
-- =============================================

CREATE OR REPLACE TABLE FEATURES_AGGREGATED AS
WITH 
class_survival AS (
    SELECT 
        PCLASS,
        ROUND(AVG(SURVIVED), 4) AS CLASS_SURVIVAL_RATE
    FROM RAW_TITANIC 
    GROUP BY PCLASS
),

sex_survival AS (
    SELECT 
        SEX,
        ROUND(AVG(SURVIVED), 4) AS SEX_SURVIVAL_RATE
    FROM RAW_TITANIC 
    GROUP BY SEX
),

title_survival AS (
    SELECT 
        TITLE,
        ROUND(AVG(SURVIVED), 4) AS TITLE_SURVIVAL_RATE
    FROM FEATURES_BASIC 
    GROUP BY TITLE
),

class_avg_fare AS (
    SELECT 
        PCLASS,
        ROUND(AVG(FARE), 2) AS CLASS_AVG_FARE
    FROM RAW_TITANIC 
    GROUP BY PCLASS
)

SELECT 
    fb.PASSENGERID,
    fb.SURVIVED,
    fb.PCLASS,
    fb.SEX,
    fb.AGE,
    fb.SIBSP,
    fb.PARCH,
    fb.FARE,
    fb.EMBARKED,
    fb.FAMILY_SIZE,
    fb.IS_ALONE,
    fb.HAS_CABIN,
    fb.TITLE,
    
    cs.CLASS_SURVIVAL_RATE,
    ss.SEX_SURVIVAL_RATE,
    ts.TITLE_SURVIVAL_RATE,
    cf.CLASS_AVG_FARE
    
FROM FEATURES_BASIC fb
LEFT JOIN class_survival cs ON fb.PCLASS = cs.PCLASS
LEFT JOIN sex_survival ss ON fb.SEX = ss.SEX
LEFT JOIN title_survival ts ON fb.TITLE = ts.TITLE
LEFT JOIN class_avg_fare cf ON fb.PCLASS = cf.PCLASS;

SELECT COUNT(*) AS FEATURES_AGGREGATED_ROWS FROM FEATURES_AGGREGATED;
SELECT * FROM FEATURES_AGGREGATED LIMIT 5;

-- =============================================
-- STEP 4: HANDLE MISSING VALUES
-- =============================================

CREATE OR REPLACE TABLE FEATURES_CLEANED AS
SELECT 
    PASSENGERID,
    SURVIVED,
    PCLASS,
    SEX,
    SIBSP,
    PARCH,
    EMBARKED,
    FAMILY_SIZE,
    IS_ALONE,
    HAS_CABIN,
    TITLE,
    CLASS_SURVIVAL_RATE,
    SEX_SURVIVAL_RATE,
    TITLE_SURVIVAL_RATE,
    CLASS_AVG_FARE,
    
    COALESCE(AGE, MEDIAN(AGE) OVER (PARTITION BY PCLASS)) AS AGE,
    COALESCE(FARE, MEDIAN(FARE) OVER ()) AS FARE
    
FROM FEATURES_AGGREGATED;

SELECT 
    COUNT(*) - COUNT(AGE) AS MISSING_AGE,
    COUNT(*) - COUNT(FARE) AS MISSING_FARE
FROM FEATURES_CLEANED;

SELECT * FROM FEATURES_CLEANED LIMIT 5;

-- =============================================
-- STEP 5: ENCODING - CONVERT TEXT TO NUMBERS
-- =============================================

CREATE OR REPLACE TABLE FEATURES_ENCODED AS
SELECT 
    PASSENGERID,
    SURVIVED,
    PCLASS,
    AGE,
    FARE,
    SIBSP,
    PARCH,
    FAMILY_SIZE,
    IS_ALONE,
    HAS_CABIN,
    CLASS_SURVIVAL_RATE,
    SEX_SURVIVAL_RATE,
    TITLE_SURVIVAL_RATE,
    CLASS_AVG_FARE,
    
    CASE WHEN SEX = 'male' THEN 1 ELSE 0 END AS SEX_MALE,
    CASE WHEN SEX = 'female' THEN 1 ELSE 0 END AS SEX_FEMALE,
    
    CASE WHEN EMBARKED = 'C' THEN 1 ELSE 0 END AS EMBARKED_C,
    CASE WHEN EMBARKED = 'Q' THEN 1 ELSE 0 END AS EMBARKED_Q,
    CASE WHEN EMBARKED = 'S' THEN 1 ELSE 0 END AS EMBARKED_S,
    
    CASE WHEN TITLE = 'Mr' THEN 1 ELSE 0 END AS TITLE_MR,
    CASE WHEN TITLE = 'Mrs' THEN 1 ELSE 0 END AS TITLE_MRS,
    CASE WHEN TITLE = 'Miss' THEN 1 ELSE 0 END AS TITLE_MISS,
    CASE WHEN TITLE = 'Master' THEN 1 ELSE 0 END AS TITLE_MASTER,
    CASE WHEN TITLE = 'Other' THEN 1 ELSE 0 END AS TITLE_OTHER
    
FROM FEATURES_CLEANED;

SELECT COUNT(*) AS FEATURES_ENCODED_ROWS FROM FEATURES_ENCODED;
SELECT * FROM FEATURES_ENCODED LIMIT 5;

-- =============================================
-- STEP 6: NORMALIZATION (Z-SCORE)
-- =============================================

CREATE OR REPLACE TABLE FEATURES_NORMALIZED AS
WITH stats AS (
    SELECT 
        AVG(AGE) AS mean_age,
        STDDEV(AGE) AS std_age,
        AVG(FARE) AS mean_fare,
        STDDEV(FARE) AS std_fare,
        AVG(FAMILY_SIZE) AS mean_family,
        STDDEV(FAMILY_SIZE) AS std_family
    FROM FEATURES_ENCODED
)
SELECT 
    fe.PASSENGERID,
    fe.SURVIVED,
    fe.PCLASS,
    fe.SIBSP,
    fe.PARCH,
    fe.FAMILY_SIZE,
    fe.IS_ALONE,
    fe.HAS_CABIN,
    fe.SEX_MALE,
    fe.SEX_FEMALE,
    fe.EMBARKED_C,
    fe.EMBARKED_Q,
    fe.EMBARKED_S,
    fe.TITLE_MR,
    fe.TITLE_MRS,
    fe.TITLE_MISS,
    fe.TITLE_MASTER,
    fe.TITLE_OTHER,
    fe.CLASS_SURVIVAL_RATE,
    fe.SEX_SURVIVAL_RATE,
    fe.TITLE_SURVIVAL_RATE,
    fe.CLASS_AVG_FARE,
    
    ROUND((fe.AGE - s.mean_age) / s.std_age, 6) AS AGE_NORMALIZED,
    ROUND((fe.FARE - s.mean_fare) / s.std_fare, 6) AS FARE_NORMALIZED,
    ROUND((fe.FAMILY_SIZE - s.mean_family) / s.std_family, 6) AS FAMILY_SIZE_NORMALIZED
    
FROM FEATURES_ENCODED fe
CROSS JOIN stats s;

SELECT COUNT(*) AS FEATURES_NORMALIZED_ROWS FROM FEATURES_NORMALIZED;
SELECT * FROM FEATURES_NORMALIZED LIMIT 5;

-- =============================================
-- STEP 7: FEATURE STORE
-- =============================================

CREATE OR REPLACE TABLE FEATURE_STORE (
    ENTITY_ID INTEGER,
    FEATURE_NAME VARCHAR(100),
    FEATURE_VALUE FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO FEATURE_STORE (ENTITY_ID, FEATURE_NAME, FEATURE_VALUE)
SELECT PASSENGERID, 'AGE_NORMALIZED', AGE_NORMALIZED FROM FEATURES_NORMALIZED
UNION ALL
SELECT PASSENGERID, 'FARE_NORMALIZED', FARE_NORMALIZED FROM FEATURES_NORMALIZED
UNION ALL
SELECT PASSENGERID, 'FAMILY_SIZE', FAMILY_SIZE FROM FEATURES_NORMALIZED
UNION ALL
SELECT PASSENGERID, 'IS_ALONE', IS_ALONE FROM FEATURES_NORMALIZED
UNION ALL
SELECT PASSENGERID, 'HAS_CABIN', HAS_CABIN FROM FEATURES_NORMALIZED
UNION ALL
SELECT PASSENGERID, 'SEX_MALE', SEX_MALE FROM FEATURES_NORMALIZED
UNION ALL
SELECT PASSENGERID, 'CLASS_SURVIVAL_RATE', CLASS_SURVIVAL_RATE FROM FEATURES_NORMALIZED
UNION ALL
SELECT PASSENGERID, 'SEX_SURVIVAL_RATE', SEX_SURVIVAL_RATE FROM FEATURES_NORMALIZED;

SELECT COUNT(*) AS FEATURE_STORE_RECORDS FROM FEATURE_STORE;
SELECT DISTINCT FEATURE_NAME FROM FEATURE_STORE;

-- =============================================
-- STEP 8: RETRIEVE FEATURES FROM STORE
-- =============================================

CREATE OR REPLACE VIEW FEATURE_RETRIEVAL AS
SELECT 
    ENTITY_ID,
    MAX(CASE WHEN FEATURE_NAME = 'AGE_NORMALIZED' THEN FEATURE_VALUE END) AS AGE_NORMALIZED,
    MAX(CASE WHEN FEATURE_NAME = 'FARE_NORMALIZED' THEN FEATURE_VALUE END) AS FARE_NORMALIZED,
    MAX(CASE WHEN FEATURE_NAME = 'FAMILY_SIZE' THEN FEATURE_VALUE END) AS FAMILY_SIZE,
    MAX(CASE WHEN FEATURE_NAME = 'IS_ALONE' THEN FEATURE_VALUE END) AS IS_ALONE,
    MAX(CASE WHEN FEATURE_NAME = 'HAS_CABIN' THEN FEATURE_VALUE END) AS HAS_CABIN,
    MAX(CASE WHEN FEATURE_NAME = 'SEX_MALE' THEN FEATURE_VALUE END) AS SEX_MALE,
    MAX(CASE WHEN FEATURE_NAME = 'CLASS_SURVIVAL_RATE' THEN FEATURE_VALUE END) AS CLASS_SURVIVAL_RATE,
    MAX(CASE WHEN FEATURE_NAME = 'SEX_SURVIVAL_RATE' THEN FEATURE_VALUE END) AS SEX_SURVIVAL_RATE
FROM FEATURE_STORE
GROUP BY ENTITY_ID;

SELECT * FROM FEATURE_RETRIEVAL LIMIT 10;

-- =============================================
-- STEP 9: PREPARE TRAINING DATA
-- =============================================

CREATE OR REPLACE TABLE TRAIN_DATA AS
SELECT 
    PASSENGERID,
    SURVIVED,
    AGE_NORMALIZED,
    FARE_NORMALIZED,
    FAMILY_SIZE,
    IS_ALONE,
    HAS_CABIN,
    SEX_MALE,
    PCLASS,
    CLASS_SURVIVAL_RATE,
    SEX_SURVIVAL_RATE
FROM FEATURES_NORMALIZED
WHERE MOD(PASSENGERID, 5) != 0;

CREATE OR REPLACE TABLE TEST_DATA AS
SELECT 
    PASSENGERID,
    SURVIVED,
    AGE_NORMALIZED,
    FARE_NORMALIZED,
    FAMILY_SIZE,
    IS_ALONE,
    HAS_CABIN,
    SEX_MALE,
    PCLASS,
    CLASS_SURVIVAL_RATE,
    SEX_SURVIVAL_RATE
FROM FEATURES_NORMALIZED
WHERE MOD(PASSENGERID, 5) = 0;

SELECT 'TRAIN' AS DATASET_TYPE, COUNT(*) AS ROW_COUNT FROM TRAIN_DATA
UNION ALL
SELECT 'TEST', COUNT(*) FROM TEST_DATA;

-- =============================================
-- STEP 10: ANALYSIS & INSIGHTS
-- =============================================

SELECT 
    'Survival by Class' AS ANALYSIS,
    PCLASS,
    COUNT(*) AS TOTAL_PASSENGERS,
    SUM(SURVIVED) AS SURVIVED_COUNT,
    ROUND(AVG(SURVIVED) * 100, 2) AS SURVIVAL_RATE_PCT
FROM RAW_TITANIC
GROUP BY PCLASS
ORDER BY PCLASS;

SELECT 
    SEX,
    COUNT(*) AS TOTAL,
    SUM(SURVIVED) AS SURVIVED,
    ROUND(AVG(SURVIVED) * 100, 2) AS SURVIVAL_RATE_PCT
FROM RAW_TITANIC
GROUP BY SEX;

SELECT 
    CASE 
        WHEN AGE < 18 THEN 'Child'
        WHEN AGE >= 18 AND AGE < 40 THEN 'Adult'
        ELSE 'Senior'
    END AS AGE_GROUP,
    COUNT(*) AS TOTAL,
    SUM(SURVIVED) AS SURVIVED,
    ROUND(AVG(SURVIVED) * 100, 2) AS SURVIVAL_RATE_PCT
FROM RAW_TITANIC
WHERE AGE IS NOT NULL
GROUP BY AGE_GROUP
ORDER BY AGE_GROUP;

-- =============================================

-- =============================================

-- =============================================
-- VERIFY ALL TABLES CREATED
-- =============================================

SHOW TABLES;

SELECT COUNT(*) AS RAW_DATA FROM RAW_TITANIC;
SELECT COUNT(*) AS FEATURES_BASIC_COUNT FROM FEATURES_BASIC;
SELECT COUNT(*) AS FEATURES_NORMALIZED_COUNT FROM FEATURES_NORMALIZED;
SELECT COUNT(*) AS FEATURE_STORE_COUNT FROM FEATURE_STORE;
SELECT COUNT(*) AS TRAIN_COUNT FROM TRAIN_DATA;
SELECT COUNT(*) AS TEST_COUNT FROM TEST_DATA;

SELECT 'All tables created successfully!' AS STATUS;

