-- Verify all tables created
SELECT 'PROJECT VERIFICATION' AS STATUS;

-- Count all tables
SELECT 'RAW_TITANIC' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM RAW_TITANIC
UNION ALL
SELECT 'FEATURES_BASIC', COUNT(*) FROM FEATURES_BASIC
UNION ALL
SELECT 'FEATURES_NORMALIZED', COUNT(*) FROM FEATURES_NORMALIZED
UNION ALL
SELECT 'FEATURES_PYTHON_ENHANCED', COUNT(*) FROM FEATURES_PYTHON_ENHANCED
UNION ALL
SELECT 'FEATURE_STORE', COUNT(*) FROM FEATURE_STORE
UNION ALL
SELECT 'TRAIN_DATA_PYTHON', COUNT(*) FROM TRAIN_DATA_PYTHON
UNION ALL
SELECT 'TEST_DATA_PYTHON', COUNT(*) FROM TEST_DATA_PYTHON
UNION ALL
SELECT 'FEATURE_CORRELATIONS_PYTHON', COUNT(*) FROM FEATURE_CORRELATIONS_PYTHON;

-- Feature Store Analysis
SELECT 'FEATURE STORE ANALYSIS' AS ANALYSIS;
SELECT DISTINCT FEATURE_NAME, COUNT(*) AS RECORD_COUNT
FROM FEATURE_STORE
GROUP BY FEATURE_NAME
ORDER BY FEATURE_NAME;

-- Train/Test Split Verification
SELECT 'TRAIN/TEST SPLIT' AS ANALYSIS;
SELECT 'TRAIN' AS DATASET, COUNT(*) AS COUNT FROM TRAIN_DATA_PYTHON
UNION ALL
SELECT 'TEST', COUNT(*) FROM TEST_DATA_PYTHON;

-- Sample data
SELECT 'SAMPLE DATA FROM FEATURES_PYTHON_ENHANCED' AS ANALYSIS;
SELECT * FROM FEATURES_PYTHON_ENHANCED LIMIT 10;

-- Correlations
SELECT 'FEATURE CORRELATIONS WITH SURVIVAL' AS ANALYSIS;
SELECT * FROM FEATURE_CORRELATIONS_PYTHON ORDER BY CORRELATION DESC;
TITANIC_VISTARA_PROJECT.INFORMATION_SCHEMA